
const {
  REACT_APP_CLOUDINARY_CLOUD_NAME,
  REACT_APP_CLOUDINARY_API_KEY,
  REACT_APP_CLOUDINARY_API_SECRET,
  REACT_APP_CLOUDINARY_UPLOAD_PRESET,
} = process.env;

export const CLOUDINARY_CLOUD_NAME = REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_API_KEY = REACT_APP_CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = REACT_APP_CLOUDINARY_API_SECRET;
export const CLOUDINARY_UPLOAD_PRESET = REACT_APP_CLOUDINARY_UPLOAD_PRESET;
export const CLOUDINARY_UPLOAD_ENDPOINT = `https://api.cloudinary.com/v1_1/${CLOUDINARY_UPLOAD_PRESET}/image/upload`;

export const ORDER_STATUS = {
  REQUESTING: 1,
  APPROVED: 2,
  CANCELED: 3,
  COMPLETED: 4,
};

export const EVENT_STATUS = {
  PLANNING: 1,
  PLANNED: 2,
};
